ERROR - 2024-06-19 23:16:08 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for db5015615851.hosting-data.io failed: Name or service not known in /run/media/degante/DEV/en mantenimiento/webupn/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/MySQLi/Connection.php(184): mysqli->real_connect()
#2 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#3 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
#5 /run/media/degante/DEV/en mantenimiento/webupn/system/Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#6 /run/media/degante/DEV/en mantenimiento/webupn/system/BaseModel.php(638): CodeIgniter\Model->doFindAll()
#7 /run/media/degante/DEV/en mantenimiento/webupn/app/Controllers/FrontendController.php(29): CodeIgniter\BaseModel->findAll()
#8 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(941): App\Controllers\FrontendController->index()
#9 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#10 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#11 /run/media/degante/DEV/en mantenimiento/webupn/public/index.php(79): CodeIgniter\CodeIgniter->run()
#12 /run/media/degante/DEV/en mantenimiento/webupn/system/Commands/Server/rewrite.php(47): require_once('...')
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for db5015615851.hosting-data.io failed: Name or service not known in /run/media/degante/DEV/en mantenimiento/webupn/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/MySQLi/Connection.php(184): mysqli->real_connect()
#1 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
#4 /run/media/degante/DEV/en mantenimiento/webupn/system/Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 /run/media/degante/DEV/en mantenimiento/webupn/system/BaseModel.php(638): CodeIgniter\Model->doFindAll()
#6 /run/media/degante/DEV/en mantenimiento/webupn/app/Controllers/FrontendController.php(29): CodeIgniter\BaseModel->findAll()
#7 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(941): App\Controllers\FrontendController->index()
#8 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#9 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#10 /run/media/degante/DEV/en mantenimiento/webupn/public/index.php(79): CodeIgniter\CodeIgniter->run()
#11 /run/media/degante/DEV/en mantenimiento/webupn/system/Commands/Server/rewrite.php(47): require_once('...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for db5015615851.hosting-data.io failed: Name or service not known in /run/media/degante/DEV/en mantenimiento/webupn/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
#3 /run/media/degante/DEV/en mantenimiento/webupn/system/Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 /run/media/degante/DEV/en mantenimiento/webupn/system/BaseModel.php(638): CodeIgniter\Model->doFindAll()
#5 /run/media/degante/DEV/en mantenimiento/webupn/app/Controllers/FrontendController.php(29): CodeIgniter\BaseModel->findAll()
#6 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(941): App\Controllers\FrontendController->index()
#7 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#8 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#9 /run/media/degante/DEV/en mantenimiento/webupn/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /run/media/degante/DEV/en mantenimiento/webupn/system/Commands/Server/rewrite.php(47): require_once('...')
#11 {main}
CRITICAL - 2024-06-19 23:16:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for db5015615851.hosting-data.io failed: Name or service not known
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH/Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(638): CodeIgniter\Model->doFindAll()
 5 APPPATH/Controllers/FrontendController.php(29): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\FrontendController->index()
 7 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 8 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 9 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/run/media/degante/DEV/en mantenimiento/webupn/public/index.php')
INFO - 2024-06-19 23:16:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
WARNING - 2024-06-19 23:16:18 --> [DEPRECATED] Creation of dynamic property App\Controllers\FrontendController::$session is deprecated in APPPATH/Controllers/FrontendController.php on line 21.
 1 SYSTEMPATH/CodeIgniter.php(913): App\Controllers\FrontendController->__construct()
 2 SYSTEMPATH/CodeIgniter.php(493): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/run/media/degante/DEV/en mantenimiento/webupn/public/index.php')
ERROR - 2024-06-19 23:16:18 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for db5015615851.hosting-data.io failed: Name or service not known in /run/media/degante/DEV/en mantenimiento/webupn/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/MySQLi/Connection.php(184): mysqli->real_connect()
#2 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#3 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
#5 /run/media/degante/DEV/en mantenimiento/webupn/system/Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#6 /run/media/degante/DEV/en mantenimiento/webupn/system/BaseModel.php(638): CodeIgniter\Model->doFindAll()
#7 /run/media/degante/DEV/en mantenimiento/webupn/app/Controllers/FrontendController.php(29): CodeIgniter\BaseModel->findAll()
#8 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(941): App\Controllers\FrontendController->index()
#9 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#10 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#11 /run/media/degante/DEV/en mantenimiento/webupn/public/index.php(79): CodeIgniter\CodeIgniter->run()
#12 /run/media/degante/DEV/en mantenimiento/webupn/system/Commands/Server/rewrite.php(47): require_once('...')
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for db5015615851.hosting-data.io failed: Name or service not known in /run/media/degante/DEV/en mantenimiento/webupn/system/Database/MySQLi/Connection.php:184
Stack trace:
#0 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/MySQLi/Connection.php(184): mysqli->real_connect()
#1 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
#4 /run/media/degante/DEV/en mantenimiento/webupn/system/Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 /run/media/degante/DEV/en mantenimiento/webupn/system/BaseModel.php(638): CodeIgniter\Model->doFindAll()
#6 /run/media/degante/DEV/en mantenimiento/webupn/app/Controllers/FrontendController.php(29): CodeIgniter\BaseModel->findAll()
#7 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(941): App\Controllers\FrontendController->index()
#8 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#9 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#10 /run/media/degante/DEV/en mantenimiento/webupn/public/index.php(79): CodeIgniter\CodeIgniter->run()
#11 /run/media/degante/DEV/en mantenimiento/webupn/system/Commands/Server/rewrite.php(47): require_once('...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for db5015615851.hosting-data.io failed: Name or service not known in /run/media/degante/DEV/en mantenimiento/webupn/system/Database/MySQLi/Connection.php:229
Stack trace:
#0 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 /run/media/degante/DEV/en mantenimiento/webupn/system/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
#3 /run/media/degante/DEV/en mantenimiento/webupn/system/Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 /run/media/degante/DEV/en mantenimiento/webupn/system/BaseModel.php(638): CodeIgniter\Model->doFindAll()
#5 /run/media/degante/DEV/en mantenimiento/webupn/app/Controllers/FrontendController.php(29): CodeIgniter\BaseModel->findAll()
#6 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(941): App\Controllers\FrontendController->index()
#7 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#8 /run/media/degante/DEV/en mantenimiento/webupn/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#9 /run/media/degante/DEV/en mantenimiento/webupn/public/index.php(79): CodeIgniter\CodeIgniter->run()
#10 /run/media/degante/DEV/en mantenimiento/webupn/system/Commands/Server/rewrite.php(47): require_once('...')
#11 {main}
CRITICAL - 2024-06-19 23:16:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for db5015615851.hosting-data.io failed: Name or service not known
in SYSTEMPATH/Database/BaseConnection.php on line 428.
 1 SYSTEMPATH/Database/BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH/Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(638): CodeIgniter\Model->doFindAll()
 5 APPPATH/Controllers/FrontendController.php(29): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\FrontendController->index()
 7 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 8 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 9 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('/run/media/degante/DEV/en mantenimiento/webupn/public/index.php')
